apiVersion: v1
data:
  index.html: |
    <html>
     <head>
      <title>blue</title>
     </head>
     <body bgcolor="#11a7f7">
      <h1>V1</h1>
     </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  namespace: sandbox
  name: index-blue-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: sandbox
  labels:
    app: bg-test
    color: blue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bg-test
  template:
    metadata:
      labels:
        app: bg-test
        color: blue
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: index-blue-v1
---
