apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: cultclassik@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
      - dns01:
          azureDNS:
            clientID: AZURE_CERT_MANAGER_SP_APP_ID
            clientSecretSecretRef:
            # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
              name: azuredns-config
              key: client-secret
            subscriptionID: AZURE_SUBSCRIPTION_ID
            tenantID: AZURE_TENANT_ID
            resourceGroupName: AZURE_DNS_ZONE_RESOURCE_GROUP
            hostedZoneName: AZURE_DNS_ZONE
            # Azure Cloud Environment, default to AzurePublicCloud
            environment: AzurePublicCloud